name: bangachain
recipe: pantheon

config:
  php: "7.4"
  webroot: web
  xdebug: false
  id: 2b62a896-ca8f-4f60-a9b3-5497d8e23a8f
  site: bangachain
  framework: drupal8
  database: "mariadb:10.4"

events:
  # Clear cache after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache-rebuild --yes

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

  nodejs:
    type: node:10
    globals:
      gulp-cli: latest
    run:
      - cd $LANDO_MOUNT && npm install
      - cd $LANDO_MOUNT && gulp build

  phpmyadmin:
    type: phpmyadmin

tooling:
  gulp:
    service: nodejs
  node:
    service: nodejs
  npm:
    service: nodejs
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  security-check:
    service: appserver
    cmd: "php vendor/sensiolabs/security-checker/security-checker security:check composer.lock"
