store: '1'
sku_prefix: null
sku_method: '1'
sku_random_digits: '6'
batch_products: '25'
increment_saver: '1'
commerce_product_bundle: discs
commerce_product_variation_bundle: discs
external_folders: {  }
flush_image_cache: '0'
expose_store: false
_core:
  default_config_hash: XX_sVBSVmbCr-OkRzwQ7lxIis0PcgwwqitdFEMn0cl4
