app_name: BangAChain
app_secret: sq0csp-xZkiLbDE1crRzvk6x6ggfE_lHalblLCmGTlMpDmrdKc
sandbox_app_id: sandbox-sq0idb-nUj1OCS4dv63HNQPYtKqQw
sandbox_access_token: EAAAEKA3c1g7pNXX-onWN2YU4ZKgg6LiP_prJVOjBXLK3Jn06D5peUrJ-qLDlN2e
production_app_id: sq0idp-jCMV1dgLnXH4-LY8PgCfTA
