_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - system.site
  - system.performance
  - commerce_payment.commerce_payment_gateway.square
  - smtp.settings
  - 'simple_sitemap_engines.*'
