_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: false
  commerce_dashboard__dashboard:
    menu_name: admin
    parent: 'menu_link_content:942bded5-1853-4272-afb5-9162f90ab30f'
    weight: 2
    expanded: false
    enabled: true
  entity__commerce_giftcard__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 3
    expanded: false
    enabled: true
  entity__commerce_order__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 4
    expanded: false
    enabled: true
  commerce_pos__base:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 6
    expanded: false
    enabled: true
  entity__commerce_product_attribute__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 7
    expanded: false
    enabled: true
  entity__commerce_product__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 8
    expanded: false
    enabled: true
  entity__commerce_promotion__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 9
    expanded: false
    enabled: true
  entity__commerce_shipping_method__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 10
    expanded: false
    enabled: true
  commerce__configuration:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 11
    expanded: false
    enabled: true
  commerce_reports__overview:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 12
    expanded: false
    enabled: true
  commerce_smart_importer__csv:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 13
    expanded: false
    enabled: true
