_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_generic_form: false
  contact_message_personal_form: false
  contact_message_team_application_form: false
  node_blog_form: false
  node_page_form: false
  node_slider_form: false
  node_team_member_form: false
  comment_comment_form: false
  comment_reviews_form: false
