initial_image_styles:
  large: large
  media_library: media_library
  medium: medium
  responsive_1150w: responsive_1150w
  responsive_1350w: responsive_1350w
  responsive_150w: responsive_150w
  responsive_1_1_1150w: responsive_1_1_1150w
  responsive_1_1_1350w: responsive_1_1_1350w
  responsive_1_1_150w: responsive_1_1_150w
  responsive_1_1_350w: responsive_1_1_350w
  responsive_1_1_550w: responsive_1_1_550w
  responsive_1_1_750w: responsive_1_1_750w
  responsive_1_1_950w: responsive_1_1_950w
  responsive_350w: responsive_350w
  responsive_4_3_1150w: responsive_4_3_1150w
  responsive_4_3_1350w: responsive_4_3_1350w
  responsive_4_3_150w: responsive_4_3_150w
  responsive_4_3_350w: responsive_4_3_350w
  responsive_4_3_550w: responsive_4_3_550w
  responsive_4_3_750w: responsive_4_3_750w
  responsive_4_3_950w: responsive_4_3_950w
  responsive_550w: responsive_550w
  responsive_750w: responsive_750w
  responsive_950w: responsive_950w
  s1200xa: s1200xa
  sc180x180: sc180x180
  sc400x400: sc400x400
  sc800x800: sc800x800
  sc870x540: sc870x540
  scaled_width_800: scaled_width_800
  square: square
  thumbnail: thumbnail
queue_image_styles:
  large: large
  media_library: media_library
  responsive_1_1_1150w: responsive_1_1_1150w
  responsive_1_1_1350w: responsive_1_1_1350w
  responsive_1_1_150w: responsive_1_1_150w
  responsive_1_1_350w: responsive_1_1_350w
  responsive_1_1_550w: responsive_1_1_550w
  responsive_1_1_750w: responsive_1_1_750w
  responsive_1_1_950w: responsive_1_1_950w
  responsive_4_3_1150w: responsive_4_3_1150w
  responsive_4_3_1350w: responsive_4_3_1350w
  responsive_4_3_150w: responsive_4_3_150w
  responsive_4_3_350w: responsive_4_3_350w
  responsive_4_3_550w: responsive_4_3_550w
  responsive_4_3_750w: responsive_4_3_750w
  responsive_4_3_950w: responsive_4_3_950w
  responsive_550w: responsive_550w
  responsive_750w: responsive_750w
  responsive_950w: responsive_950w
  scaled_width_800: scaled_width_800
  square: square
  thumbnail: thumbnail
