initial_image_styles: {  }
queue_image_styles:
  large: large
  media_library: media_library
  medium: medium
  responsive_1_1_950w: responsive_1_1_950w
  responsive_4_3_950w: responsive_4_3_950w
  responsive_950w: responsive_950w
  scaled_width_800: scaled_width_800
  splide_media: splide_media
  square: square
  thumbnail: thumbnail
