theme: bangachain
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: swiftmailer
      sender: swiftmailer
  smtp:
    none:
      formatter: SMTPMailSystem
      sender: SMTPMailSystem
  contact:
    'Contact Forms':
      formatter: SMTPMailSystem
      sender: SMTPMailSystem
