_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: bangachain
defaults:
  sender: SMTPMailSystem
  formatter: mime_mail
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
  smtp:
    none:
      sender: SMTPMailSystem
      formatter: mime_mail
  contact:
    'Contact Forms':
      sender: SMTPMailSystem
      formatter: mime_mail
