site_key: 6LdJGlcaAAAAAPrQsNRQ2g0qzjPnGCHLZmaUiNNn
secret_key: 6LdJGlcaAAAAAKPD4G4qItk40hkph0RL_7zspieK
verify_hostname: true
default_challenge: recaptcha/reCAPTCHA
error_message: 'Antibot verification failed.'
cacheable: false
_core:
  default_config_hash: jv0PKCJEOq2bOwY9RspuPZCf67ifVJ4tfTk-BfZMw8k
