show_on_admin: 0
alert_styles: "primary|Default, low urgency\r\nhigh|Extremely Important\r\n"
refresh_interval: '15'
_core:
  default_config_hash: YEjSLd1HQIdOiDkPxqaz7CqyvZrtIEUc3brlRw2RxWM
automatic_refresh: 0
