smtp_on: false
smtp_host: smtp-relay.sendinblue.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: standard
smtp_autotls: false
smtp_timeout: 30
smtp_username: bangachain2012@gmail.com
smtp_password: OmYVf1sg5IWwkFUS
smtp_from: bangachain2012@gmail.com
smtp_fromname: Bang-A-Chain
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
